class UpdateOrderInProgressStatuses < ActiveRecord::Migration
  def change
    #Order.update_all("status = 'IN_PROGRESS'", "status IN ('AWAITING_INTEGRATION_INFO','AWAITING_TRACKING','DELIVERED','DISPATCHED','PART_DISPATCHED','PART_PICKED','PENDING','PICKED','PICKING','SHIPMENT_ATTEMPT_FAIL','SHIPMENT_DELIVERED','SHIPMENT_EXCEPTION','SHIPMENT_EXPIRED','SHIPMENT_IN_TRANSIT','SHIPMENT_INFO_RECEIVED','SHIPMENT_OUT_FOR_DELIVERY','SHIPMENT_PENDING','WEIGHED')")
  end
end
